require 'fileutils'
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Part 1 Vagrant configuration: controller (wstyggS) and worker (wstyggSW)

SERVER_NAME = 'wstyggS'
WORKER_NAME = 'wstyggSW'
SERVER_IP = '192.168.56.110'
WORKER_IP = '192.168.56.111'
BOX_NAME = 'bento/ubuntu-22.04'
BOX_VERSION = '202407.23.0'
SHARED_DIR = '/vagrant/shared'

VM_BASE_FOLDER = File.join(Dir.pwd, 'vm-data')
FileUtils.mkdir_p(VM_BASE_FOLDER)
Vagrant.configure('2') do |config|
  config.vm.box = BOX_NAME
  config.vm.box_version = BOX_VERSION
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |vb|
    vb.customize ['setproperty', 'machinefolder', VM_BASE_FOLDER]
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.define SERVER_NAME do |server|
    server.vm.hostname = SERVER_NAME
    server.vm.network 'private_network', ip: SERVER_IP

    server.vm.provision 'shell', path: 'scripts/bootstrap_common.sh', args: [SERVER_NAME]
    server.vm.provision 'shell', path: 'scripts/install_k3s_server.sh', args: [SERVER_IP, SHARED_DIR]
  end

  config.vm.define WORKER_NAME do |worker|
    worker.vm.hostname = WORKER_NAME
    worker.vm.network 'private_network', ip: WORKER_IP

    worker.vm.provision 'shell', path: 'scripts/bootstrap_common.sh', args: [WORKER_NAME]
    worker.vm.provision 'shell', path: 'scripts/install_k3s_agent.sh', args: [WORKER_IP, SERVER_IP, SHARED_DIR]
  end
end
